spring:
  application:
    name: gulimall-product

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tifa
    password: rootPassword
    url: jdbc:mysql://10.200.200.1:3306/gulimall_pms

  cloud:
    nacos:
      server-addr: 10.200.200.1:8848
      config:
        import-check:
          enabled: false

  thymeleaf:
    cache: false

server:
  port: 10000

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0                 # 已删除
      logic-not-delete-value: 1            # 未删除
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl