spring:
  application:
    name: gulimall-product

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tifa
    password: rootPassword
    url: jdbc:mysql://10.200.200.1:3306/gulimall_pms

    hikari:
      minimum-idle: 10          # 最小空闲连接数
      maximum-pool-size: 50     # 连接池最大连接数（根据并发量和数据库性能调节）
      idle-timeout: 600000      # 空闲连接最大存活时间（10分钟）
      max-lifetime: 1800000     # 连接最长存活时间（30分钟）
      connection-timeout: 30000 # 等待连接的最大时长（30秒）

  cloud:
    nacos:
      server-addr: 10.200.200.1:8848
      config:
        import-check:
          enabled: false

  thymeleaf:
    cache: false
  data:
    redis:
      host: 10.200.200.1
      port: 6379
  cache:
    type: redis

server:
  port: 10000


mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0                 # 已删除
      logic-not-delete-value: 1            # 未删除
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl