spring:
  application:
    name: gulimall-product

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gulimall_pms

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false

server:
  port: 10000
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0                 # 已删除
      logic-not-delete-value: 1            # 未删除