logging:
  level:
    org.springframework.cloud.gateway: DEBUG
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      server-addr: 10.200.200.1:8848
      config:
        username: "nacos"
        password: "nacos"
    gateway:
      routes:
        - id: oss-service
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/renren-fast/oss/**
          filters:
            - StripPrefix=2

        - id: product-service
          uri: lb://gulimall-product
          predicates:
            - Path=/api/renren-fast/product/**
          filters:
            - StripPrefix=2

        - id: ware-service
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/renren-fast/ware/**
          filters:
            - StripPrefix=2

        - id: member-service
          uri: lb://gulimall-member
          predicates:
            - Path=/api/renren-fast/member/**
          filters:
            - StripPrefix=2

        - id: renren-fast
          uri: lb://renren-fast
          predicates:
            - Path=/api/renren-fast/**
          filters:
            - StripPrefix=1


        - id: gulimall-search-host
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com,*.search.gulimall.com

        - id: gulimall-host
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,*.gulimall.com,item.gulimall.com

  config:
    import:
      - nacos:gulimall-gateway.properties?refreshEnabled=true&group=DEFAULT_GROUP
server:
  port: 88

