logging:
  level:
    org.springframework.cloud.gateway: DEBUG
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        username: "nacos"
        password: "nacos"
    gateway:
      routes:
        - id: oss-service
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/renren-fast/oss/**
          filters:
            - StripPrefix=2

        - id: product-service
          uri: lb://gulimall-product
          predicates:
            - Path=/api/renren-fast/product/**
          filters:
            - StripPrefix=2

        - id: member-service
          uri: lb://gulimall-member
          predicates:
            - Path=/api/renren-fast/member/**
          filters:
            - StripPrefix=2

        - id: renren-fast
          uri: lb://renren-fast
          predicates:
            - Path=/api/renren-fast/**
          filters:
            - StripPrefix=1

  config:
    import:
      - nacos:gulimall-gateway.properties?refreshEnabled=true&group=DEFAULT_GROUP
server:
  port: 88

