logging:
  level:
    org.springframework.cloud.gateway: DEBUG
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        username: "nacos"
        password: "nacos"
    gateway:
      routes:
        - id: test_route
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: http://www.qq.com
          predicates:
            - Query=url,qq


        - id: product-service
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1

        - id: oss-service
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/oss/get_post_signature_for_oss_upload/**
          filters:
            - StripPrefix=1

  config:
    import:
      - nacos:gulimall-gateway.properties?refreshEnabled=true&group=DEFAULT_GROUP
server:
  port: 88

