spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        username: "nacos"
        password: "nacos"
    gateway:
      routes:
        - id: test_route
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: http://www.qq.com
          predicates:
            - Query=url,qq
  config:
    import:
      - nacos:gulimall-gateway.properties?refreshEnabled=true&group=DEFAULT_GROUP
server:
  port: 88

